### ISSUE TITLE
This is scam project

### ISSUE THREAD

**Issue by jamesVectorspace** [thopatevijay/SmartGenie#5]
dont connect your wallet. This is scam project.!!!!

**Comment by Vossip** [comment]
These are some quite strong accusations, @jamesVectorspace.

Could you provide more details or evidence to support your claim? I take these kinds of concerns seriously and would like to understand your perspective better.

**Comment by thopatevijay** [comment]
Hello,

I received your email regarding a comment on my project, SmartGenie. I
would like to address the concerns raised.

*Project Overview*: SmartGenie is an AI-powered assistant for Solidity
developers, aimed at enhancing productivity and code quality by providing
comprehensive reviews, suggestions, and interactive modifications.

*Clarifications*:

*No Fund Handling*: The project does not involve any kind of fund
transactions.

*Testnet Usage*: It operates solely on testnets/devnets and only signs
transactions to the testnet. The relevant configuration is:

NEXT_PUBLIC_RPC_URL_GALADRIEL="https://devnet.galadriel.com"
NEXT_PUBLIC_SOLIDITY_CODE_AGENT_CONTRACT_ADDRESS=0xE43ea4bb5fb44C6cBD29573Df307991c7070BB03

https://github.com/thopatevijay/SmartGenie/blob/9083a9f5a55a7d3e670410b99218788f83939c60/.env.local.example#L4C1-L5C92

*Transparency and Verification*: All contract addresses and codes are
public for verification.

The comment by @jamesVectorspace appears to be a baseless accusation. I am
confident in the integrity of my project and open to any further
verification you may require.

Thank you for your understanding.

Best Regard,

Vijay.

**Comment by thopatevijay** [comment]
Hello,

I received your email regarding a comment on my project, SmartGenie. I would like to address the concerns raised.

Project Overview: SmartGenie is an AI-powered assistant for Solidity developers, aimed at enhancing productivity and code quality by providing comprehensive reviews, suggestions, and interactive modifications.

Clarifications:

No Fund Handling: The project does not involve any kind of fund transactions.

Testnet Usage: It operates solely on testnets/devnets and only signs transactions to the testnet. The relevant configuration is:

NEXT_PUBLIC_RPC_URL_GALADRIEL="https://devnet.galadriel.com"
NEXT_PUBLIC_SOLIDITY_CODE_AGENT_CONTRACT_ADDRESS=0xE43ea4bb5fb44C6cBD29573Df307991c7070BB03

https://github.com/thopatevijay/SmartGenie/blob/9083a9f5a55a7d3e670410b99218788f83939c60/.env.local.example#L4C1-L5C92

Transparency and Verification: All contract addresses and codes are public for verification.

The comment by @jamesVectorspace appears to be a baseless accusation. I am confident in the integrity of my project and open to any further verification you may require.

Thank you for your understanding.

Best Regard,

Vijay.

**Comment by jamesVectorspace** [comment]
Smart contract was not verified and when click the review button, metamask is saying "Be careful" alert

**Comment by thopatevijay** [comment]
You can have a look here to see how AI can be implemented inside the smart contract.

**Comment by jamesVectorspace** [comment]
Oh, I see.
why is the metamask saying "Scam Alert"?

**Comment by thopatevijay** [comment]
> Oh, I see. why is the metamask saying "Scam Alert"?

Can you please share screen shots where metamask is showing `Scam Alert: ?

**Comment by thopatevijay** [comment]
> Please verify your smart contract. so i can check it

Will do that surely.

**Comment by jamesVectorspace** [comment]
![image](https://github.com/thopatevijay/SmartGenie/assets/132741740/88e3db53-5466-4e9d-b412-e414cd0cea35)

**Comment by thopatevijay** [comment]
> ![image](https://private-user-images.githubusercontent.com/132741740/345133794-88e3db53-5466-4e9d-b412-e414cd0cea35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NDE4MDksIm5iZiI6MTcxOTk0MTUwOSwicGF0aCI6Ii8xMzI3NDE3NDAvMzQ1MTMzNzk0LTg4ZTNkYjUzLTU0NjYtNGU5ZC1iNDEyLWU0MTRjZDBjZWEzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQxNzMxNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTI5NDY3NzRlZDI3NDYyNGEwYTc0MzUyNzk4NmExNDBiZjM2Yzk3YzgxOGU4NWU3MWU1OGIxMjZjYTFjZTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GUkcc9Thln66NSvzV6QJmfHR0_60_dJeZRMZ2ggNyl8)



Hahahah, Good try.

But I dont see warning, see below:

![image](https://github.com/thopatevijay/SmartGenie/assets/58559626/5188813b-2db8-4930-93d9-5626a5373aef)

**Comment by thopatevijay** [comment]
Make sure that while interacting with app, you need to setup the wallet like below
https://docs.galadriel.com/setting-up-a-wallet

**Comment by jamesVectorspace** [comment]
hmmm, I see.
what is your contract info?

**Comment by jamesVectorspace** [comment]
You, too. LOL
